#!/usr/bin/env python3
"""Embed gaggiano-v2/web/index.html into gaggiano-v2/web_page.h as a C string.

Run by ./gg build; the output is committed so a plain arduino-cli build works too.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "gaggiano-v2", "web", "index.html")
OUT = os.path.join(ROOT, "gaggiano-v2", "web_page.h")

html = open(SRC, encoding="utf-8").read()
if ')html"' in html:
    sys.exit("index.html must not contain the raw-string terminator )html\"")
body = ('// Generated by tools/embed-web.py from web/index.html. Do not edit.\n'
        '#pragma once\n'
        '#include <pgmspace.h>\n'
        'static const char WEB_INDEX_HTML[] PROGMEM = R"html(' + html + ')html";\n')
old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
if body != old:
    open(OUT, "w", encoding="utf-8").write(body)
    print("web_page.h regenerated (%d bytes of HTML)" % len(html))
